### ISSUE TITLE
Implementar sistema de registro

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Back-end#11]
LA APi del sistema de registro, que reciba parametros, los compruebe etc y registre un usuario. Mirar la API de google (https://developers.google.com/identity/openid-connect/openid-connect?hl=es-419) que quizá nos aporta beneficios

**Comment by Juanguppy** [comment]
Hecho.

**Comment by Juanguppy** [comment]
revisadlo y hago merge con main, lo he prbado con una herramienta que te permite hacer peticiones http

**Comment by FabiMur** [comment]
Creo que es mejor tener separados los routes de express de los queries a la  BBDD. Rollo tener una especie de ""DAO"" crearUsuario que sea llamado con el route de express. Asi queda mas limpio,  se separan funcionalidades y podemos reutilizar codigo. Me encargo yo de esto. Por lo demas bien.

**Comment by Juanguppy** [comment]
Tienes razón había olvidado el tema del DAO, sí que es necesario para que el modelo sea intependiente de la capa de datos. Es simplemente cambiar las llamaads a la bdd por llamadas a funcion tipo dao.existeUsuario(...) y dao.insertarUsuario(...)
