### ISSUE TITLE
Implementar el chat

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Back-end#13]
Para implementar los chats he estado investigando estas alternativas: 
1. RabbitMQ: https://www.rabbitmq.com/tutorials/tutorial-one-javascript (es una cola de mensajes, a priori no parece muy complicada de hacer y chatgpt parece que la conoce)
2. Hacerlo ' a pelo ' -> Usuario envía mensaje a chat grupal, se almacena en la BD y los usuarios lo recuperan de la BD

**Comment by FabiMur** [comment]
Que aporta exactamente la opción de RabbitMQ?

**Comment by FabiMur** [comment]
Sigue habiendo si o si que leer y almacenar los mensajes en la BBDD. Si he entendido bien lo que he leído Rabbit es para **mensajería asíncrona entre aplicaciones**, que no es lo que necesitamos.

**Comment by Juanguppy** [comment]
Hecho, al final utilicé la opción fácil. Faltaría el sistema de notificaciones que asumo va en #23

**Comment by Juanguppy** [comment]
Reabro, falta operación que permite obtener todos los mensajes de un chat, y obtener todos los chats de un jugador (es trivial, se me olvidó)

**Comment by Juanguppy** [comment]
lo marco como bug para que no se me olvide pero no es un bug
