### ISSUE TITLE
Implementar empezar partida

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Back-end#14]
Recibir una petición del front que inicie una nueva partida

**Comment by Juanguppy** [comment]
hecho

**Comment by 737275** [comment]
¿Se ha considerado qué hacer con las invitaciones a la hora de iniciar una partida? Quizás podría tener sentido invalidar todas las invitaciones una vez se empiece.

**Comment by Juanguppy** [comment]
al final qué hacemos con esto? @737275

**Comment by Juanguppy** [comment]
> ¿Se ha considerado qué hacer con las invitaciones a la hora de iniciar una partida? Quizás podría tener sentido invalidar todas las invitaciones una vez se empiece.

Esto no concierne a este issue, este issue es "Crear partida", no "empezar partida creada". Concierne a #20
