### ISSUE TITLE
Implementar lógica de obtener todas las partidas públicas

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Back-end#18]

**Comment by Juanguppy** [comment]
Hecho

**Comment by 737275** [comment]
Realmente interesan todas las partidas, no únicamente las públicas, ya que estamos implementando una lista de servidores. Si es privada, tendrá una contraseña, pero sigue siendo necesario ser capaz de verla.

**Comment by 737275** [comment]
También es necesario borrar una partida (cuando el host abandona el servidor antes de empezarla, no cuando termina una partida).

**Comment by Juanguppy** [comment]
> Realmente interesan todas las partidas, no únicamente las públicas, ya que estamos implementando una lista de servidores. Si es privada, tendrá una contraseña, pero sigue siendo necesario ser capaz de verla.

No necesariamente. De hecho no tiene sentido que puedas ver las partidas privadas en una lista, pues por algo son privadas, ¿no?
Lo suyo es que las públicas sean accesibles mediante una lista de partidas (parecido a los servidores de Club Penguin o a las partidas del Supremacy1914) , y las privadas no aparezcan en esa lista, porque habrá mucha gente que pondrá password=123 y es fácil que se le cuele gente (no me acuerdo que juego lo tenía así y me acuerdo que me dedicaba a colarme en partidas de gente probando 123 de password xD). 

Lo suyo es que las privadas solo puedas entrar en otro sitio, mandando un formulario <nombre> <password> (como en Among Us, por ejemplo) o bien por invitación (como en el LoL). 

No tiene sentido mostrar las partidas privadas en la misma lista que las públicas y creo que así se reflejó en los requisitos en su momento y así lo decidimos ya. Se podría debatir y si hay más gente que piense como tú podemos cambiarlo, no me importa, pero lo creo innecesario y me suena que ya lo hablamos y en los requisitos así se refleja

**Comment by Juanguppy** [comment]
> También es necesario borrar una partida (cuando el host abandona el servidor antes de empezarla, no cuando termina una partida).

Esto no es de este Issue, y sí, tienes razón. Es necesario implementar esa funcionalidad  que simplemente sería un "eliminar partida" y que el front end lo llame en varias situaciones: 

- Abandona el host antes de empezarla
- La partida se rinde
- La partida excede un timeout en el que todos están afk (?)

**Comment by 737275** [comment]
Privada no significa oculta, una partida es privada sale en la lista de partidas disponibles, pero con una contraseña. Es así la implementación de servidores en muchos juegos. Sin embargo, no me parece mal tampoco esta aproximación. Simplemente dejo este comentario como documentación.

Me parece bien hacerlo con un issue a parte porque has sacado varios ejemplos de que puede ser una funcionalidad algo más compleja, pero por norma general cuando implementemos una funcionalidad deberíamos implementar el CRUD completo, en mi opinión.
