### ISSUE TITLE
Implementar lógica de 'empezar partida' creada

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Back-end#20]
donde se empieza una partida creada previamente y comienza a ejecutarse un juego nuevo

**Comment by FabiMur** [comment]
Continuar una partida pausada no?

**Comment by Juanguppy** [comment]
> Continuar una partida pausada no? O pasar de lo que seria el ""lobby"" de la partida a jugar por primera vez?

Pasar del lobby a jugar por primera vez: la partida está guardada en la BDD como no iniciada, y se comprueba si tiene el número de jugadores mínimo para poder jugar y se pasa a iniciada y en el estado se empiezan a gaurdar los turnos y mandar notificaciones al primer jugador

**Comment by GuilleLita** [comment]
Esto tiene que ser un boton desde el Front que sea iniciar partida, lo implento y leugo vemos

**Comment by GuilleLita** [comment]
De todas maneras, creo que hay que darle una vuelta a lo de identificar partidas, pondría un ID único para cada partida así da igual si tienen mismo nombre y password.

**Comment by GuilleLita** [comment]
Lo que he hecho de momento es comprobar que todas las condiciones para que una partida se de por empezada se cumplen y ponerlo a iniciada.

Comentarme si hace falta algo mas.

**Comment by Juanguppy** [comment]
está bien pero en vez de buscar por id y password, buscaría por OID, yque en el req.body te pasen el OID 
si se busca por id y password hay que buscar que además la partida esté not(finalizada) y que contenga al user que invoca a la función

**Comment by Juanguppy** [comment]
para esto hay q cambiar la función "nuevaPartida" junto con el documento de la API y que devuelva la partida completa , creo que es incluso más logico porque así el front end puede mostrar más info sobre la misma (nombre, jugadores, etc) y el OID guardarselo en la sesión o localstorage como si fuese un identificador más que no necesariamente ha de ser el _id de mongoDB

**Comment by Juanguppy** [comment]
@GuilleLita @FabiMur tendreis que cambiarlo para que solo empiece <-> han votado todos los jugadores q esztán dentro que están ready && se ha alcanzado el numero mínimo de jugadores 
para ello, hay q añadir cosas en la BD en el schema partida, si quereis puedo hacerlo yo pero creo que renta más si lo hjaceis vosotros ya q es vuestro issue aunque tb me afecta a mi en el crear partida
