### ISSUE TITLE
Implementar sistema de amigos

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Back-end#21]
1. Enviar solicitudes
2. Aceptar solicitudes
3. Eliminar solicitudes
4. Notificar a los front de nueva solicitud (Tendremos q usar publish subscribe o algo así)

**Comment by Juanguppy** [comment]
ya estaría hecho no? faltaría lo de notificar que técnicamente es una funcionalidad aparte

**Comment by 737275** [comment]
Faltan los tests, issue #33.
