### ISSUE TITLE
Implementar módulo de gestión de invitaciones a partidas

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Back-end#24]
- Módulo que permite invitar a amigos a partidas privadas

**Comment by 737275** [comment]
Apunto posibles ideas para la implementación:

- Enviar una notificación al front con la que poder unirse una vez, que envíe la contraseña y la use para unir. Se podría también parametrizar la función de unir para que no necesite contraseña si es una invitación. Esta implementación es válida únicamente cuando el usuario está conectado.
- Guardar una lista de invitados en la base de datos. Tiene la funcionalidad completa al implementar persistencia pero implica una modificación del modelo de datos.

Me decanto por la persistencia dado que es la implementación completa. Estoy abierto a otras implementaciones, estas son las que se me han ocurrido, es posible que exista alguna mejor.

**Comment by 737275** [comment]
Quedan los tests automáticos y un par de funcionalidades que necesita este módulo: obtener la lista de amigos de un usuario y la lista de sus partidas invitadas.
