### ISSUE TITLE
Consulta del histórico de partidas de un usuario

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Back-end#29]
- Programar un sistema que permita al usuario obtener el histórico de partidas jugadas, así como 
su resultado

**Comment by 737275** [comment]
El usuario es una entidad con clave primaria simple, por lo que voy a utilizarla en lugar del OID para el campo "usuario" de "jugadores" en "partida". La ventaja es una concordancia con el valor obtenido por el token de autentificación.

**Comment by 737275** [comment]
Cierro el issue, pero las pruebas automáticas deberían ser más extensas, que es dependiente del issue #19.

**Comment by Juanguppy** [comment]
"PARA QUE ESTOS TESTS FUNCIONEN, PERRO SANXE TIENE QUE TENER AL MENOS UNA PARTIDA Y PIGDEMON NINGUNA"
Hombre, lo suyo es que prepares tú el entorno antes de correr un test, ¿no? no puede haber un test que funciona a veces sí y a veces no, tienes que asegurarte tú de que las precondiciones del test se cumplen antes de que este corra. No reabro, pero creo nuevo issue 'tests de histórico + unirse a partida'

**Comment by Juanguppy** [comment]
Te copio lo que he puesto en el código. Tampoco es dependiente del issue #19 como dices, de hecho es un test unitario, no puede depender de nada (más que del login ya que obvaiemnte necesitas el auth.token) 

 // Este test por deifinición, tal y como está, no sirve para nada, un test que no verifica las precodinciones no tiene sentido
// Si se desea obtener el histórico de partidas de un usuario, primero debes crear un usuario ' a pelo ' que tenga
// unas partidas determinadas en unas serias, y luego en el test verificarlo. No tiene sentido coger un usuario cualquiera
// y confiar en que no habrá cambiado desde la última vez que se ejecutó el test. Lo comento, porque no tiene sentido. 
// No es un test automático, es un test manual. Dependes de que vaya alguien a la base de datos y cambie las partidas
// de pigdemon y perro sanxe, lo cual no es el objetivo de los tests automáticos. Mira como se han hecho el resto de tests. 
// Una buena aproximación para este test sería la siguiente: 
// 1. If sanchez tiene al menos una partida -> do nothing ; else -> añadir una partida a sanchez (se puede hacer a pelo, no necesitas
// la lógica de unirse a una partida). 
// 2. If pigdemon tiene al menos una partida -> pigdemon.partidas = []. Y ya te aseguras de que funciona siempre, y no dependes
// de la otra funcionalidad como decías, ya que para algo es un test unitario.

**Comment by 737275** [comment]
Repito, este test estaba como base para implementarlo más extensamente. Había pensado en tener una dependencia para aprovechar la API, pero sí me parece mala idea tener dependencias en pruebas unitarias. De todas formas, si reabres este issue, no me crees otro.
