### ISSUE TITLE
banco de pruebas crear partida

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Back-end#36]

**Comment by 737275** [comment]
Una pruebas que pueda fallas por causas aleatorias no es un buen test. Al crear partida, asegúrate de que no exista la partida que vayas a crear, y luego créala.

**Comment by Juanguppy** [comment]
de momento está hecho, ya no falla por causas aleatorias siempre que estemos en un entorno de desarrollo. Cuando cambiéis la base de datos, cosa que no está dentro de mis competencias por no tener el issue asignado, cambiaré el test.
