### ISSUE TITLE
Crear diagrama Entidad-Relación

### ISSUE THREAD

**Issue by 737275** [UNIZAR-30226-2024-02/Back-end#4]
Crear el diagrama Entidad-Relación para la base de datos a utilizar en la aplicación y subirlo a GitHub.

**Comment by FabiMur** [comment]
Subido en el drive y branch BBDD del back-end

**Comment by 737275** [comment]
¿Es necesaria la relación ternaria? Suelen dar problemas a la hora de implementar y se podría aplicar una alternativa sencilla con dos relaciones. Se debería también desarrollar el atributo "Estado" de la entidad "Partida", es posible que se complique y no sea suficiente con un atributo.

**Comment by FabiMur** [comment]
Con respecto al chat no tenia muy claro como representarlo en el ER, pero creo que la idea de la implementación esta bien. Tienes una entidad chat completamente independiente y luego cada partida tiene asociado un chat. 

El atributo "Estado" es un atributo compuesto. En el ER no lo desarrolle por simplicidad, pero en la implementación esta. Y no es lo mismo que hacer otra entidad separada, mas bien es un conjunto de atributos de la misma entidad agrupados. De la forma que esta puesto ahora el estado se almacena junto a la partida y no es una entidad independiente.

**Comment by Juanguppy** [comment]
Tal y como está implementado, se puede modelar en el ER como una entidad Mensaje, relacionada con su chat (en este caso el array de mensajes lo guarda chat) y con "mandado por" se relaciona con el jugador. Luego lo cambio porque es mejor así y mas fiel a la posterior implementación

Lo de Estado lo veo bien como atributo, pensando en que la BD es mongo, aunque conceptualmente lo pondría como entidad y una relación 1:1.

**Comment by FabiMur** [comment]
El estado del juego tiene que estar como atributo, no tiene sentido otra cosa. El estado esta contenido **dentro** del doc partida, no tiene relación con ningun otro doc, no tiene identificador y no se accede a el de forma independiente.

Lo de los mensajes no lo veo del todo claro la verdad. La implementacion es la que es. En el ER sigo pensando que es una relación ternaria. Cada mensaje esta  asociado a un **jugador** y a un **chat** concretos. Si mensaje se relaciona solo con chat y chat solo con jugador, no estas expresando que cada mensaje fue mandado por un jugador concreto.

**Comment by Juanguppy** [comment]
pues al menos poner los atributos de los q está compuesto ese atributo "estado" o indicar el tipo como un dato estructurado compuesto por varios atributos en una anotación porque tal y como está parece que es algo de un tipo primitivo 

los mensajes tal y como están implementados en mongo no son una relación ternaria aunque conceptualmente no está mal que lo sea (pues lo que se quiere modelar se ve bastante claro) pero en general se deben evitar este tipo de relaciones y pienso que debería existir consistencia entre el ER y la implementación

**Comment by FabiMur** [comment]
Lo del estado pensaba ponerlo como un anexo o algo pq es un atributo con un monton de campos, lo mismo pasa ahora con info adicional de usaurio. He puesto un comentario en el ER.

Las relaciones ternarias existen,  no es que siempre esten mal. Un mensaje esta relacionado con un jugador (el que lo manda) y con un chat(en el que se manda). Hasta aqui podrian ser 2 relaciones binarias. Pero un mensaje solo lo puede mandar un jugador que esta en el chat asociado al mensaje y solo puede ser mandado en un chat en el que esta el jugador que manda el mensaje. Cierro el issue pq esto ya es coña ahora hay mas cosas que hacer, mas adelante si cambia la cosa se modifica. 

Kind regards :heart:

**Comment by 737275** [comment]
No lo reabro pero tendremos que revisitarlo para que refleje lo que implementamos. Por ejemplo las cartas, los territorios, los turnos, parece que se almacenan en la relación con el jugador.

Misma historia con la ternaria, parece que estamos implementando: "Mensaje" con "Usuario" y luego "Mensaje" con "Chat".

En un principio estos aspectos no son conceptualmente incorrectos.
