### ISSUE TITLE
Usuario solo puede crear chat con sus amigos

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Back-end#42]
- Hacer que devuelva un error si un usuario intenta crear un chat con una persona que no es su amiga, ya que tal y como está ahora permitimos que añada a cualquier persona con solo saber su id. Se podría hacer que si no es su amigo y lo intenta añdir a un chat le redirija a la pantalla de solicitudes de amistad (tema del front)

**Comment by GuilleLita** [comment]
Asi quedaria
![Screenshot 2024-03-21 094500](https://github.com/UNIZAR-30226-2024-02/Back-end/assets/32071767/4d898213-564d-4696-b444-1ffa1adbea32)

**Comment by GuilleLita** [comment]
Funciona, pero ahora no manda error si los usuarios que has enviado no existen, aunque creo que da igual porque solo meto los que son amigos y existen al chat. lo dejo abierto por esto.

**Comment by Juanguppy** [comment]
> Funciona, pero ahora no manda error si los usuarios que has enviado no existen, aunque creo que da igual porque solo meto los que son amigos y existen al chat. lo dejo abierto por esto.

quizá que de error no es buena idea tampoco, pero que como parte de la HTTP reply devuevla algo así como 
"no se añadió a [listausuariosnoañadidos] por no ser tus amigos / no existir", de modo que los de front end puedan  mostrar una notificación al usuario de que no se han añadido esos usuarios. Aunque es un caso hipote´tico, tecnicamente el usuario nunca va a poder enviar una solicitud a usuarios inexistentes

**Comment by Juanguppy** [comment]
así que eso debe corregirse, y también los unit tests asociados a esta función

**Comment by GuilleLita** [comment]
Habría que cambiar el documento de la API para reflejar este nuevo mesaje

**Comment by Juanguppy** [comment]
ya he actualizado el documento de la api, creo q se puede cerrar ya
