### ISSUE TITLE
Estandarizar HTTP status codes

### ISSUE THREAD

**Issue by 737275** [UNIZAR-30226-2024-02/Back-end#46]
Deberíamos conocer y seguir los códigos según el estándar. Wikipedia tiene un resumen rápido:

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

Abro el issue para que todos seamos conscientes, no cuesta nada y quedamos bien.

**Comment by Juanguppy** [comment]
no tiene mucho sentido q nos asignes a todos, todos tenemos q saberlo pero solo uno debería ser el encargado de corregir los que ya están 'mal'

**Comment by 737275** [comment]
El objetivo era notificar a todos para que sean conscientes, pero puedo ponerme como responsable e ir persiguiendo a la gente como policía cuando no lo hagan.

**Comment by Juanguppy** [comment]
> Member

pues escribamos un documento de cómo deben realizarse los códigos de error y hagámoselo llegar a todos

**Comment by 737275** [comment]
No es necesario un documento, siguiendo las reglas descritas en el estándar es suficiente. Todo lo que escriba yo, o cualquiera de nosotros va a estar peor explicado.
