### ISSUE TITLE
Crear base de datos MONGODB en Atlas

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Back-end#8]
A partir del esquema E/R, crear la base de datos mongoDB utilizando Atlas

**Comment by FabiMur** [comment]
Creada, falta terminar de definir la estructura de EstadoPartida y Mapa. Añadire algun ejemplo de uso a la rama BBDD de back-end.

**Comment by FabiMur** [comment]
Modelos y prueba de conexión en rama BBDD

**Comment by FabiMur** [comment]
Es similar pq hice un merge💀
Lo que hubo que cambiar alguna cosa, por ejemplo los parametros que se le pasaban al connect segun la doc ya no estan soportados y con ellos no va.

**Comment by Juanguppy** [comment]
La rama 6 (la de crear el esqueleto) contiene una versión más actualizada en la que arreglé esos errores (fallo mio por hacer mal el merge XD) quizá esa rama junto con la de BDD ya se puedan hacer merge con el main y arreglar los conflictos (que da igual porque son dos versiones similares)
