### ISSUE TITLE
Revisar fronteras

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Back-end#87]
- Sigue habiendo algunas mal, por ejemplo españa no es alcanzable desde marruecos pero realmente sí q debria

**Comment by FabiMur** [comment]
😆😆😆 si has visto algo mal las vuelvo a revisar. Lo estuve mirando aquí btw [https://es.wikipedia.org/wiki/Risk]( https://es.wikipedia.org/wiki/Risk )

**Comment by Juanguppy** [comment]
> 😆😆😆 si has visto algo mal las vuelvo a revisar. Lo estuve mirando aquí btw https://es.wikipedia.org/wiki/Risk

vale, es que el SVG es distinto ;-; tenemos q decidir uno u otro

**Comment by FabiMur** [comment]
Sunpongo que lo mas facil es que lo cambie yo en la lógica...
