### ISSUE TITLE
Definir la conexión con la base de datos y su API

### ISSUE THREAD

**Issue by Juanguppy** [UNIZAR-30226-2024-02/Back-end#9]
A partir de la base de datos creada en atlas, y a partir de los diagramas de secuencias, crear el módulo que permite la conexión con la BD y su API

**Comment by Juanguppy** [comment]
Hecha la conexión en la rama asociada a este Issue. Falta probar con la conexión de Atlas + algo del back end que permita ejecutar (aunque sea un hello world)

**Comment by Juanguppy** [comment]
Mirar para hacer un pool que es mejor (de momento podemos usar esto pero el proyecto final tinee que tener un pool)

**Comment by Juanguppy** [comment]
Al parecer Mongo ya te crea el pool solo y te lo medio gestiona (https://mongoosejs.com/docs/connections.html), si lo he entendido bien

**Comment by 737275** [comment]
Lo cierro para continuar la discusión en #16, me parece que están relacionados.
